### ISSUE TITLE
doesn't compil under visual studio 2017

### ISSUE THREAD

**Issue by devkenzor** [badaix/aixlog#6]
Hello,

Just to let you know, your code can't compil under Visual Studio 2017 due to a compilation bug:

error C2216: 'explicit' can't be used with 'virtual' for the line 287.

It is a bug in visual studio as explicit should be usable with virtual, but visual studio has this bug from the 2013 version, so I don't expect a fix soon.

Great job anyway, just one more question that is not in the documentation: is your logging library thread-safe?

**Comment by badaix** [comment]
I'm wondering why I made these functions virtual. There is actually no need to do so. No one derives from them or should change the behaviour of this operator.
The `virtual` specifier is removed in [v1.2.1](https://github.com/badaix/aixlog/releases/tag/v1.2.1).
And yes, it is thread safe.
